# Generated by Django 3.0.5 on 2021-12-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='salary',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='teacher/'),
        ),
    ]
