# Generated by Django 3.0.5 on 2021-12-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='question_number',
            new_name='no_of_questions',
        ),
    ]
